using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using System;

public class Dialog_Text : MonoBehaviour
{
    //Scripts
    //[HideInInspector]
    //public MouseRay S_MouseRay;

    //+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++


    //DIALOGUE ARRAYS
    //Takeru
    //delegate void D_DialogsTakeru();

    

    //Dialog Texts
    [HideInInspector] 
    public string[] A_Dialog_Takeru_General = new string[14];
    [HideInInspector]
    public string[] A_Dialog_Takeru_Correct = new string[11];
    [HideInInspector] 
    public string[] A_Dialog_Takeru_Wrong = new string[5];

    [HideInInspector]
    public string[] A_Dialog_Mamoru_General = new string[15];
    [HideInInspector]
    public string[] A_Dialog_Mamoru_Correct = new string[16];
    [HideInInspector]
    public string[] A_Dialog_Mamoru_Wrong = new string[8];

    [HideInInspector] 
    public string[] A_Dialog_Nanami_General = new string[13];
    [HideInInspector]
    public string[] A_Dialog_Nanami_Correct = new string[8];
    [HideInInspector]
    public string[] A_Dialog_Nanami_Wrong = new string[3];


    //+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++


    //START
    void Start()
    {
        //S_MouseRay = GameObject.Find("GameManager").GetComponent<MouseRay>();
        //Dialogue_TakeruGeneral();

        //+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++


        Dialog_TakeruGeneral();
        Dialog_TakeruCorrect();
        Dialog_TakeruWrong();

        Dialog_MamoruGeneral();
        Dialog_MamoruCorrect();
        Dialog_MamoruWrong();

        Dialog_NanamiGeneral();
        Dialog_NanamiCorrect();
        Dialog_NanamiWrong();



    }

    //UPDATE
    void Update()
    {

        //A_Dialog_Mamoru_Correct.Add("ģHier, bitte sehr.Ģ ");


    }

    //+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++


    //FUNCTIONS

    //+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    //Names

   


    //+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    //Takeru

    public void Dialog_TakeruGeneral() /* Dialogue || 1 || */
    {
        Debug.Log(A_Dialog_Takeru_General.Length);

        //Takeru enters Restaurant
        //CharaCount=0 Index=0-13 DialogCount=0

        /*T 2.1 = [8]*/ A_Dialog_Takeru_General[0]  = "ģHey!Ģ ";  
        /*T 1.1 = [0]*/ A_Dialog_Takeru_General[1]  = "*Puts down Umbrella* ";        
        /*P 2.2 = [9]*/ A_Dialog_Takeru_General[2]  = "ģOh, hello, Takeru. You're quite early today?Ģ ";        
        /*T 1.2 = [1]*/ A_Dialog_Takeru_General[3]  = "ģYes, there is a competition at the garden center today! There will be the prettiest hydrangeas around!Ģ ";        
        /*P 1.1 = [0]*/ A_Dialog_Takeru_General[4]  = "ģSounds great! Did you submit any?Ģ ";        
        /*T 1.5 = [4]*/ A_Dialog_Takeru_General[5]  = "ģUm, well.. not really.Ģ ";        
        /*P 1.4 = [3]*/ A_Dialog_Takeru_General[6]  = "ģWhy not?Ģ ";        
        /*T 1.6 = [5]*/ A_Dialog_Takeru_General[7]  = "ģDunno... Mine are nice, but they don't measure up to those of professional gardeners.Ģ ";       
        /*P 1.4 = [3]*/ A_Dialog_Takeru_General[8]  = "ģDon't talk such nonsense! Next year you will take part in the competition.Ģ ";        
        /*T 1.6 = [5]*/ A_Dialog_Takeru_General[9]  = "ģWell... Let's see.Ģ ";          
        /*P 1.4 = [3]*/ A_Dialog_Takeru_General[10] = "ģDon't make that face. What will you have today?Ģ ";         
        /*T 1.7 = [6]*/ A_Dialog_Takeru_General[11] = "ģId like Tonbara. To go please.Ģ ";        
        /*P 1.8 = [7]*/ A_Dialog_Takeru_General[12] = "ģSure.Ģ ";         
        /*P 2.1 = [1]*/ A_Dialog_Takeru_General[13] = "*Making food* ";       

    }
    public void Dialog_TakeruCorrect() /* Dialogue || 1.Correct || */
    {
        //Takeru enters Restaurant
        //CharaCount=0 Index=0-10 DialogCount=1

        /*P 1.8 = [7]*/ A_Dialog_Takeru_Correct[0]  = "ģHere you are.Ģ ";
        /*T 1.7 = [6]*/ A_Dialog_Takeru_Correct[1]  = "ģThank you.Ģ ";
        /*P 1.8 = [7]*/ A_Dialog_Takeru_Correct[2]  = "ģHey, how did your date go?Ģ ";
        /*T 1.6 = [5]*/ A_Dialog_Takeru_Correct[3]  = "ģActually quite well. I think I just laid on too thick.Ģ ";
        /*P 1.3 = [3]*/ A_Dialog_Takeru_Correct[4]  = "ģYou?Ģ ";
        /*T 1.5 = [4]*/ A_Dialog_Takeru_Correct[5]  = "ģI don't know... It went very well, first we went for ice cream, and then we walked through the park, but I don't think they shared my passion for flowers. Maybe I shouldn't have emphasized the whole time that I've never eaten a human...Ģ ";
        /*P 1.3 = [2]*/ A_Dialog_Takeru_Correct[6]  = "ģOh, I'm sorry. I'm sure it'll be better next time. Concentrate on the beautiful hydrangeas today, they will surely distract you!Ģ ";
        /*T 1.7 = [6]*/ A_Dialog_Takeru_Correct[7]  = "ģOh yes! That's right, I have to go! Thanks, I'll take photos for you!Ģ ";
        /*P 1.8 = [7]*/ A_Dialog_Takeru_Correct[8]  = "ģHave a nice day!Ģ ";
        /*P Gone  */    A_Dialog_Takeru_Correct[9]  = "*Gives money and leaves, forgets the umbrella* ";
        /*P Gone  */    A_Dialog_Takeru_Correct[10] = "ģTakeru! Your umbrella! Oh, he's already gone. Then I'll stow it away until he comes back.Ģ ";

    }
    public void Dialog_TakeruWrong() /* Dialogue || 1.Wrong || */
    {
        //Takeru enters Restaurant
        //CharaCount=0 Index=0-4 DialogCount=3

        /*P 1.8 = [7]*/ A_Dialog_Takeru_Wrong[0] = "ģHere you are.Ģ ";
        /*T 1.7 = [6]*/ A_Dialog_Takeru_Wrong[1] = "ģThank you! Then I have to leave quickly! Have a great day.Ģ ";
        /*P 1.8 = [7]*/ A_Dialog_Takeru_Wrong[2] = "ģYou too!Ģ ";
        /*T LEAVES  */  A_Dialog_Takeru_Wrong[3] = "*Gives money and leaves, forget the umbrella*  ";
        /*P Gone  */    A_Dialog_Takeru_Wrong[4] = "ģTakeru! Your umbrella! Oh, he's already gone. Then I'll stow it away until he comes back.Ģ ";





        //FINDING CALLS


    }


    //+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    //Mamoru

    public void Dialog_MamoruGeneral() /* Dialog || 2 || */
    {
        //Takeru enters Restaurant
        //CharaCount=1 Index=0-13 DialogCount=0

        /*M 2.3 = [6]*/ A_Dialog_Mamoru_General[0] = "ģHello, my favorite chef!Ģ ";
        /*P 2.3 = [6]*/ A_Dialog_Mamoru_General[1] = "ģDon't let my colleagues hear that.Ģ ";
        /*M 2.2 = [5]*/ A_Dialog_Mamoru_General[2] = "*Laughs* ";
        /*P 2.3 = [6]*/ A_Dialog_Mamoru_General[3] = "ģTell me, how are you?Ģ ";
        /*M 1.2 = [1]*/ A_Dialog_Mamoru_General[4] = "ģOh, better than ever. Everything is just fine right now.Ģ ";
        /*P 1.1 = [0]*/ A_Dialog_Mamoru_General[5] = "ģI'm glad.Ģ *hesitates* ģSay, could you do me a favor?Ģ ";
        /*M 1.1 = [0]*/ A_Dialog_Mamoru_General[6] = "ģOf course! What is it?Ģ ";
        /*P 1.1 = [0]*/ A_Dialog_Mamoru_General[7] = "ģYou remember the little Y?rei?Ģ ";
        /*M 2.1 = [4]*/ A_Dialog_Mamoru_General[8] = "ģSure, how is she? Is she still there?Ģ ";
        /*P 2.1 = [4]*/ A_Dialog_Mamoru_General[9] = "ģYes, and I tried to talk to her. She said she was afraid of something, but didn't say what. Can you find out for me? As a Baku, you can see people's concerns. Is that also possible with Y?rei?Ģ ";
        /*M 2.1 = [4]*/ A_Dialog_Mamoru_General[10] = "ģHm I don't know. But I can try it.Ģ ";
        /*P 2.3 = [6]*/ A_Dialog_Mamoru_General[11] = "ģOh, thank you! Say, what ramen do you want? Then I can get it started.Ģ ";
        /*M 2.3 = [6]*/ A_Dialog_Mamoru_General[12] = "ģOh, Kikaku please.Ģ ";
        /*P 2.3 = [6]*/ A_Dialog_Mamoru_General[13] = "ģOf course.Ģ ";
        /*P 2.3 = [6]*/ A_Dialog_Mamoru_General[14] = "*Making food* ";

    }
    public void Dialog_MamoruCorrect() /* Dialog || 2.Correct || */
    {
        //Takeru enters Restaurant
        //CharaCount=1 Index=0-15 DialogCount=1

        /*p 1.1 = [0]*/ A_Dialog_Mamoru_Correct[0]  = "ģHere, your ramen. Enjoy your meal.Ģ ";
        /*m 1.3 = [2]*/ A_Dialog_Mamoru_Correct[1]  = "ģAnd I have more good news too! The little one is afraid of water.Ģ ";
        /*p 1.3 = [2]*/ A_Dialog_Mamoru_Correct[2]  = "ģWater? Why?Ģ ";
        /*m 2.1 = [4]*/ A_Dialog_Mamoru_Correct[3]  = "ģWell, you'll have to ask her that yourself.Ģ ";
        /*p 2.1 = [4]*/ A_Dialog_Mamoru_Correct[4]  = "ģThank you, Mamoru. Maybe I can help her somehow.Ģ ";
        /*m 2.3 = [6]*/ A_Dialog_Mamoru_Correct[5]  = "ģI am sure of that. You've got a knack for it.Ģ ";
        /*p 2.3 = [6]*/ A_Dialog_Mamoru_Correct[6]  = "ģHow is it going with your Arashi?Ģ ";
        /*m 2.2 = [5]*/ A_Dialog_Mamoru_Correct[7]  = "ģI gave him my spare key now.Ģ ";
        /*p 2.2 = [5]*/ A_Dialog_Mamoru_Correct[8]  = "ģUh, how romantic.Ģ ";
        /*m 2.3 = [6]*/ A_Dialog_Mamoru_Correct[9]  = "ģNot really, I have to buy everything twice. So now I have a toothbrush in every apartment.Ģ";
        /*p 2.3 = [6]*/ A_Dialog_Mamoru_Correct[10] = "ģWell, then you'll have to move in together.Ģ ";
        /*m 2.1 = [4]*/ A_Dialog_Mamoru_Correct[11] = "ģI don't know if we're ready for that yet... Even though we're actually always together.Ģ ";
        /*p 1.2 = [1]*/ A_Dialog_Mamoru_Correct[12] = "ģOh, don't stress. You still have plenty of time.Ģ ";
        /*m 1.2 = [1]*/ A_Dialog_Mamoru_Correct[13] = "ģYou're right. I'll go eat. Finding out a fear like that makes you hungry.Ģ ";
        /*p 1.2 = [1]*/ A_Dialog_Mamoru_Correct[14] = "ģThank you again! Bon appétit!Ģ ";
        /*m LEAVES   */ A_Dialog_Mamoru_Correct[15] = "*Gives money and sits down in the back* ";


    }
    public void Dialog_MamoruWrong() /* Dialog || 2.Wrong || */
    {
        //Takeru enters Restaurant
        //CharaCount=1 Index=0-7 DialogCount=2

        /*p 1.1 = [0]*/ A_Dialog_Mamoru_Wrong[0] = "ģHere, your ramen. Enjoy your meal.Ģ ";
        /*m 1.3 = [2]*/ A_Dialog_Mamoru_Wrong[1] = "ģAnd I have more good news too! The little one is afraid of water.Ģ ";
        /*p 1.3 = [2]*/ A_Dialog_Mamoru_Wrong[2] = "ģWater? Why?Ģ ";
        /*m 2.1 = [4]*/ A_Dialog_Mamoru_Wrong[3] = "ģWell, you'll have to ask her that yourself.Ģ ";
        /*p 2.1 = [4]*/ A_Dialog_Mamoru_Wrong[4] = "ģThank you, Mamoru. Maybe I can help her somehow.Ģ ";
        /*m 2.3 = [5]*/ A_Dialog_Mamoru_Wrong[5] = "ģI am sure of that. You've got a knack for it. I'll go sit in the back, finding out a fear like that makes you hungryĢ ";
        /*p 1.2 = [1]*/ A_Dialog_Mamoru_Wrong[6] = "ģThank you again! Bon appétit!Ģ ";
        /*m LEAVES   */ A_Dialog_Mamoru_Wrong[7] = "*Gives money and sits down in the back* ";
    }


    //+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    // Nanami

    public void Dialog_NanamiGeneral() /* Dialog || 3. || */
    {
        //Takeru enters Restaurant
        //CharaCount=2 Index=0-12 DialogCount=0

        /*n 1.3 = [2]*/  A_Dialog_Nanami_General[0] = "*silently coming up to the counter* ";
        /*p 1.3 = [2]*/  A_Dialog_Nanami_General[1] = "ģOh hello. How can I help you?Ģ ";
        /*n 1.4 = [3]*/  A_Dialog_Nanami_General[2] = "ģI'm hungry.Ģ ";
        /*p 2.3 = [8]*/  A_Dialog_Nanami_General[3] = "ģLuckily, this is a restaurant. So, what would you like?Ģ ";
        /*n 2.5 = [10]*/ A_Dialog_Nanami_General[4] = "ģ... I have no money.Ģ ";
        /*p 2.6 = [11]*/ A_Dialog_Nanami_General[5] = "ģOh... take your pick anyway.Ģ ";
        /*n 2.1 = [6]*/  A_Dialog_Nanami_General[6] = "*silence* ";
        /*p 2.1 = [6]*/  A_Dialog_Nanami_General[7] = "ģOn the house. Come on, what would you like?Ģ ";
        /*n 1.4 = [3]*/  A_Dialog_Nanami_General[8] = "ģWhat's delicious?Ģ ";
        /*p 1.3 = [2]*/  A_Dialog_Nanami_General[9] = "ģHmm well, my favorite is Tonbara, although that's a bit odd. Maybe you'd rather have the classic, the Kikaku.Ģ ";
        /*n 1.6 = [5]*/  A_Dialog_Nanami_General[10] = "ģThe one you like.Ģ ";
        /*p 1.3 = [2]*/  A_Dialog_Nanami_General[11] = "ģOkay, coming right away.Ģ ";
        /*p 1.3 = [2]*/  A_Dialog_Nanami_General[12] = "*Making food*  ";

    }
    public void Dialog_NanamiCorrect() /* Dialog || 3.Correct || */
    {
        //Takeru enters Restaurant
        //CharaCount=2 Index=0-6 DialogCount=1

        /*p 1.3 = [2]*/  A_Dialog_Nanami_Correct[0] = "ģHere you go. Enjoy your meal.Ģ ";
        /*n 1.5 = [4]*/  A_Dialog_Nanami_Correct[1] = "ģThank you.Ģ ";
        /*n 1.3 = [2]*/  A_Dialog_Nanami_Correct[2] = "*Silence* ";
        /*p 2.1 = [6]*/  A_Dialog_Nanami_Correct[3] = "ģNanami? Are you alright?Ģ ";
        /*n 2.2 = [7]*/  A_Dialog_Nanami_Correct[4] = "ģI... don't want to eat alone.Ģ ";
        /*p 2.3 = [8]*/  A_Dialog_Nanami_Correct[5] = "ģHmm I'll be done in ten minutes. Can you wait that long?Ģ ";
        /*n 2.4 = [9]*/ A_Dialog_Nanami_Correct[6] = "ģHmm.Ģ *nods*Ģ ";
        /*n LEAVES   */  A_Dialog_Nanami_Correct[7] = "*Leaves the counter*  ";

    }
    public void Dialog_NanamiWrong() /* Dialog || 3.Wrong || */
    {
        //Takeru enters Restaurant
        //CharaCount=2 Index=0-1 DialogCount=2

        /*p 1.3 = [2]*/ A_Dialog_Nanami_Wrong[0] = "ģHere you go.Ģ ";
        /*n 1.5 = [4]*/ A_Dialog_Nanami_Wrong[1] = "ģThanks.Ģ ";
        /*n LEAVES   */ A_Dialog_Nanami_Wrong[2] = "*Hesitates, then leaves* ";

    }




    //+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++


    //FINDING CALLS




}
